for WAZO-1960: check multiple scopes
wazo-platform/wazo-auth pull request #106
Opened 2020-09-09 21:06 UTC by bloom1

Depends-On: https://github.com/wazo-platform/wazo-auth-client/pull/15

2020-09-10 18:49 UTC, sduthil requested changes

2020-09-10 18:49 UTC, sduthil commented on integration_tests/suite/test_http_interface.py
> +            )
A test is missing: if client is in a subtenant, checking against a top tenant should return 403.

2020-09-10 18:49 UTC, sduthil commented on integration_tests/suite/test_http_interface.py
> +                token, ['foo'], tenant='55ee61f3-c4a5-427c-9f40-9d5c33466240'
Magic number here: could you replace with a constant like `UNKNOWN_TENANT`?

2020-09-10 18:49 UTC, sduthil commented on wazo_auth/plugins/http/tokens/http.py
> +class TenantCheckMixin:
Nice deduplication!
However, I'd prefer this logic to be in the service rather than the HTTP interface.
Also, I'd prefer this to be a function rather than a mixin method. The Mixin class uses `self._user_services`, but this attribute is defined in the other class.

2020-09-10 18:49 UTC, sduthil commented on wazo_auth/services/token.py
> +            scope_statuses[scope] = token.matches_required_acl(scope)
More Pythonic:
```python
scope_statuses = {scope: token.matches_required_acl(scope) for scope in set(scopes)}
```

2020-09-10 18:49 UTC, sduthil commented on wazo_auth/services/token.py
> +            raise UnknownTokenException()
Nice catch :) Wouldn't have thought of that one. Too bad we can't test it...

2020-09-10 18:49 UTC, sduthil commented on wazo_auth/plugins/http/tokens/api.yml
> +        - $ref: '#/parameters/tenant'
Thank you for fixing this!

2020-09-11 02:38 UTC, sduthil approved these changes

2020-09-11 13:25 UTC, bloom1 commented
regate

2020-09-11 13:42 UTC, bloom1 commented
recheck

2020-09-11 18:09 UTC, bloom1 commented
recheck

2020-09-11 19:10 UTC, merged