Wazo 2287 tenant slug
wazo-platform/wazo-auth pull request #137
Opened 2021-03-17 19:10 UTC by pc-m

2021-03-17 19:32 UTC, pc-m commented
> SonarCloud Quality Gate failed.
> 
> [<img alt="Bug" width="16" height="16" src="https://camo.githubusercontent.com/deaad8c9d9b09977da3f9aa455689440a17356bb359560328463022a0d9d1362/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f6275672e706e67">](https://sonarcloud.io/project/issues?id=wazo-platform_wazo-auth&pullRequest=137&resolved=false&types=BUG) [<img alt="A" width="16" height="16" src="https://camo.githubusercontent.com/c51bc537468c04ce22bf2a646097b829e435b6847a82d6e663dd26de8ba24fc5/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412e706e67">](https://sonarcloud.io/project/issues?id=wazo-platform_wazo-auth&pullRequest=137&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=wazo-platform_wazo-auth&pullRequest=137&resolved=false&types=BUG)
> [<img alt="Vulnerability" width="16" height="16" src="https://camo.githubusercontent.com/60273222b26453a76e9c369287fa0106b151cbaae4fa4ce00e149b269a0fac67/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f76756c6e65726162696c6974792e706e67">](https://sonarcloud.io/project/issues?id=wazo-platform_wazo-auth&pullRequest=137&resolved=false&types=VULNERABILITY) [<img alt="A" width="16" height="16" src="https://camo.githubusercontent.com/c51bc537468c04ce22bf2a646097b829e435b6847a82d6e663dd26de8ba24fc5/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412e706e67">](https://sonarcloud.io/project/issues?id=wazo-platform_wazo-auth&pullRequest=137&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=wazo-platform_wazo-auth&pullRequest=137&resolved=false&types=VULNERABILITY)
> [<img alt="Security Hotspot" width="16" height="16" src="https://camo.githubusercontent.com/a0723b4c04ec36cc8d010cca748afdc6300592f020130edca7403ea5b17ffe35/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f73656375726974795f686f7473706f742e706e67">](https://sonarcloud.io/project/security_hotspots?id=wazo-platform_wazo-auth&pullRequest=137&resolved=false&types=SECURITY_HOTSPOT) [<img alt="E" width="16" height="16" src="https://camo.githubusercontent.com/d1da85f351e00bba6c56d3810244c6e8db2ac21477a0ebfb29caf57027619c72/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f452e706e67">](https://sonarcloud.io/project/security_hotspots?id=wazo-platform_wazo-auth&pullRequest=137&resolved=false&types=SECURITY_HOTSPOT) [2 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=wazo-platform_wazo-auth&pullRequest=137&resolved=false&types=SECURITY_HOTSPOT)
> [<img alt="Code Smell" width="16" height="16" src="https://camo.githubusercontent.com/1b640677486022b878fa0367aa2b5cffad9b009d2ff2fc3440cbd7f8da85fe55/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f636f64655f736d656c6c2e706e67">](https://sonarcloud.io/project/issues?id=wazo-platform_wazo-auth&pullRequest=137&resolved=false&types=CODE_SMELL) [<img alt="A" width="16" height="16" src="https://camo.githubusercontent.com/c51bc537468c04ce22bf2a646097b829e435b6847a82d6e663dd26de8ba24fc5/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412e706e67">](https://sonarcloud.io/project/issues?id=wazo-platform_wazo-auth&pullRequest=137&resolved=false&types=CODE_SMELL) [1 Code Smell](https://sonarcloud.io/project/issues?id=wazo-platform_wazo-auth&pullRequest=137&resolved=false&types=CODE_SMELL)
> 
> [<img alt="No Coverage information" width="16" height="16" src="https://camo.githubusercontent.com/eacd0d319c038e3339874e3166c6eaf3d0c647fae1a11b0f95225ea6d35302d4/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f436f76657261676543686172742f4e6f436f766572616765496e666f2e706e67">](https://sonarcloud.io/component_measures?id=wazo-platform_wazo-auth&pullRequest=137) No Coverage information
> [<img alt="0.0%" width="16" height="16" src="https://camo.githubusercontent.com/17c8580971832aaa80226d5b1c5c61cc2f9ef6a863fc6f6bae0ab2c7d45165ed/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f4475706c69636174696f6e732f332e706e67">](https://sonarcloud.io/component_measures?id=wazo-platform_wazo-auth&pullRequest=137&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=wazo-platform_wazo-auth&pullRequest=137&metric=new_duplicated_lines_density&view=list)

My auto-generated slugs do not need to be safe. Thanks for checking

2021-03-19 13:46 UTC, fblackburn1 requested changes

2021-03-19 13:46 UTC, fblackburn1 commented on alembic/versions/9b80db8b7860_add_tenant_slug.py
> +            slug = tenant.name.replace(' ', '_').replace('-', '_')
We should check/replace for all non `a-zA-Z0-9_` char
To avoid emoji ............. :sweat:

2021-03-19 13:46 UTC, fblackburn1 commented on wazo_auth/schemas.py
> +class TenantFullSchema(BaseSchema):
You can inherit from `TenantPUTSchema` and only add slug field to avoid copy/paste other fields
Or inherit `TenantPUTSchema` from `TenantFullSchema` and define slug as `dump_only`

2021-03-19 13:46 UTC, fblackburn1 commented on wazo_auth/plugins/http/tenants/api.yml
> +        description: "A unique, human readeable identifier for this tenant. This field cannot be modified."
add note about autogenerated if empty

2021-03-19 13:46 UTC, fblackburn1 commented on wazo_auth/database/queries/tenant.py
> +                return slug
Should we try to use name to create slug, because a random string of 10 is really annoying when you cannot update it after.
What do you think to generate a smaller  (3-4) slug than the maximum authorized char. I'll mitigate this ugly 10 random char

2021-03-19 13:47 UTC, fblackburn1 commented on alembic/versions/9b80db8b7860_add_tenant_slug.py
> +    sa.column('slug'),
```suggestion
    sa.Column('slug'),
```

2021-03-19 15:42 UTC, pc-m commented
All fixed, thanks!

2021-03-19 17:17 UTC, fblackburn1 commented
recheck

2021-03-19 17:25 UTC, fblackburn1 approved these changes

2021-03-19 18:05 UTC, merged