WP-494: active directory compatiblity
wazo-platform/wazo-auth pull request #197
Opened 2022-01-20 21:48 UTC by bloom1

Essentially, it is already compatible. The important part is that Microsoft uses a particular DN format.
It looks like: `CN=Firstname Lastname,DN=Users,DC=domain,DC=ext` instead of the usual `CN=Firstname Lastname,OU=People,DC=domain,DC=ext`
However, I added some tests to support some cases I stumbled upon.

2022-01-24 20:56 UTC, pc-m reviewed
The "link" between the ldap user and the Wazo should user should be done using the wazo-auth user instead of using the `find_by` from xivo-dao.
Is it planned for another story?

2022-01-24 21:17 UTC, bloom1 commented
> 

No it is not planned in another story. Good point, I will get rid of that monstrosity in this ticket directly.

Thank you!

2022-01-26 14:44 UTC, pc-m requested changes
`get_metadata` should be modified to find the purpose of the user and generate the metadata from the purpose plugin associated to that purpose.

The change should be pretty simple if you inspire yourself from the wazo_user plugin.

2022-01-31 21:43 UTC, bloom1 commented
> 

Hello @pc-m, I have an issue with the metadata plugin:

Given the LDAP is configured for a login with a DN of `CN=Alice Wonderland,OU=people,OU=quebec,DC=wazo,DC=io` then the username is `Alice Wonderland`. It means that that LDAP username MUST match the one in the wazo-auth database. Do we really want an association of the username, given we already have the email association?

2022-02-01 21:01 UTC, bloom1 commented
> > `get_metadata` should be modified to find the purpose of the user and generate the metadata from the purpose plugin associated to that purpose.
> > The change should be pretty simple if you inspire yourself from the wazo_user plugin.
> 
> Hello @pc-m, I have an issue with the metadata plugin:
> 
> Given the LDAP is configured for a login with a DN of `CN=Alice Wonderland,OU=people,OU=quebec,DC=wazo,DC=io` then the username is `Alice Wonderland`. It means that that LDAP username MUST match the one in the wazo-auth database. Do we really want an association of the username, given we already have the email association?

Forget what I said, I am able ot add an email address to the `args` that is passed around and it works wonderfully :smile:

2022-02-02 18:50 UTC, pc-m approved these changes

2022-02-02 20:11 UTC, merged