WAZO-2673: ldap login with config
wazo-platform/wazo-auth pull request #202
Opened 2022-02-07 22:03 UTC by bloom1

Based on https://github.com/wazo-platform/wazo-auth/pull/200

2022-02-10 15:48 UTC, bloom1 commented
recheck

2022-02-10 19:03 UTC, pc-m requested changes

2022-02-10 19:34 UTC, bloom1 commented on wazo_auth/plugins/backends/ldap_user.py
> +    def _get_user_uuid_by_ldap_attribute(self, user_email, tenant_uuid):
Oh my bad, alright I agree with that :smiley:

2022-02-11 13:20 UTC, pc-m approved these changes

2022-02-11 13:34 UTC, merged