WAZO-2497 bus inject tenant_uuid
wazo-platform/wazo-auth pull request #204
Opened 2022-02-10 16:41 UTC by ja0x

2022-02-11 18:23 UTC, fblackburn1 requested changes
every work as expected :+1:

2022-02-11 18:23 UTC, fblackburn1 commented on wazo_auth/token.py
> +            headers = {'tenant_uuid': tenant_uuid} if tenant_uuid else None
Don't use `get` when `tenant_uuid` is always defined in `event_args`

```suggestion
            tenant_uuid = event_args['tenant_uuid']
            headers = {'tenant_uuid': tenant_uuid} if tenant_uuid else None
```
or
```suggestion
            headers = None
            if event_args['tenant_uuid']:
                headers = {'tenant_uuid': event_args['tenant_uuid']}
```

2022-02-11 18:23 UTC, fblackburn1 commented on integration_tests/suite/test_external.py
> +            print(msg)
Not the first time you forget `print`. You can add pre-commit hook to detect them. [Example](https://github.com/wazo-platform/xivo-tools/blob/master/git-hooks/local-docker-volume-check)
```suggestion
```

2022-02-11 18:23 UTC, fblackburn1 commented on integration_tests/suite/test_external.py
> +            msg = msg_accumulator.accumulate(with_headers=True)
I guess you move this line outside of the `assert_that` only to print result?

2022-02-14 13:28 UTC, ja0x commented on wazo_auth/services/external_auth.py
> +            return user['tenant_uuid']
IndexError is to catch out of bound errors, meaning returning None if no user are in the list returned by the query.  I do agree with the previous statement, the exception should be raised letting the program know that the requested user does not exist rather than silently returning none, will be changed

2022-02-14 13:37 UTC, ja0x commented on integration_tests/suite/test_external.py
> +            print(msg)
:see_no_evil:
Good idea with the hook

2022-02-14 15:12 UTC, fblackburn1 commented on wazo_auth/token.py
> +        headers = {}
I don't think it's a good practice to reuse same dict for different purpose/value.
Should be defined just before the `if event_args['tenant_uuid']`

2022-02-14 16:18 UTC, fblackburn1 approved these changes

2022-02-14 16:34 UTC, merged