Add domain_names field to wazo-auth
wazo-platform/wazo-auth pull request #219
Opened 2022-04-05 14:53 UTC by nissou91

**Reason:**

As a developer, I would like to be able to set a list of domain names for my tenant.

**Constraints:**

* Must be unique,
* Must contain valid domain names,
* Must support all CRUD operations,
* Must support search for a specific domain_name

2022-04-08 01:48 UTC, nissou91 commented
recheck

2022-04-19 18:28 UTC, nissou91 commented
recheck

2022-04-26 15:01 UTC, pc-m commented on wazo_auth/database/models.py
> +    uuid = Column(
Could you move the `uuid` field before `name`. We usually put primary keys at the beginning of the schema definition.

2022-04-26 15:10 UTC, pc-m commented on wazo_auth/database/alembic/versions/0c9ccb1b16a8_add_auth_tenant_domain_name.py
> +    op.create_unique_constraint('auth_tenant_domain_name_key', TABLE_NAME, ['name'])
The `create_unique_constraint` is redundant with the `unique=True` in the `name` definition. You can remove it.

2022-04-26 15:15 UTC, pc-m commented on integration_tests/suite/test_db_tenant.py
> +        self, uuid, name, parent_uuid=ANY_UUID, slug=ANY, domain_names=[]
This is a python trap. You should not use an empty dict as a default argument. Use `None` instead.

2022-04-26 15:16 UTC, pc-m commented on integration_tests/suite/test_db_tenant.py
> +        if domain_names and len(domain_names) > 0:
`if domain_names:` would be enough to not enter the if if `domain_names` was `None` or an empty list

2022-04-26 15:20 UTC, pc-m commented on integration_tests/suite/test_db_tenant.py
> +            assert_that(count_, equal_to(len(domain_names)))
This only check how many domain names there are, not if they match. You should do something similar to this
```suggestion
            names = s.query(models.DomainName.name).filter(filter_).all()
            assert_that(domain_names, contains_inanyorder(names))
```

2022-04-26 15:22 UTC, pc-m commented on wazo_auth/database/queries/tenant.py
> +        if domain_names and len(domain_names) > 0:
The marshmallow schema should set the `domain_names` to be an empty list and reject `None`. You can remove this `if`

2022-04-26 15:24 UTC, pc-m commented on wazo_auth/database/queries/tenant.py
> +    def get_tenant_by_domain_name(self, domain_name):
This function is unused, it should be removed with its test and the `_check_domain_name_exists` helper method

2022-04-26 15:36 UTC, pc-m commented on wazo_auth/plugins/http/tenants/tests/test_tenants.py
> +        for field, invalid_data in invalid_datas:
This test does only 1 post with a body containing all possible wrong domain names in the same payload.
It should do a post for each of the possible value.

2022-04-28 03:01 UTC, nissou91 commented
recheck

2022-04-28 18:38 UTC, pc-m requested changes
Good job @nissou91
There some new fixes to make but it's mostly done.

2022-04-28 18:38 UTC, pc-m commented on integration_tests/suite/test_tenants.py
> +        s = t.TenantDAO().session
You can use a `GET` here and avoid the query

2022-04-28 18:38 UTC, pc-m commented on integration_tests/suite/test_tenants.py
> +                400, self.client.tenants.new, domain_names=list(invalid_domain_name)
I want to see some tests where `domain_names` is not a list.
`None`, `True`, `False`, `'wazo.community'`, `42`, `{'name': 'wazo.community'}`

2022-04-28 18:38 UTC, pc-m commented on wazo_auth/plugins/http/tenants/tests/test_tenants.py
> +        invalid_datas = [
I want to see some tests where `domain_names` is not a list.
`None`, `True`, `False`, `'wazo.community'`, `42`, `{'name': 'wazo.community'}`

2022-04-28 18:38 UTC, pc-m commented on wazo_auth/schemas.py
> +        'domain_name',
Only `domain_name` is required here.
The `searchable_columns` list contains fields that can be used in the GET (list) query string to search for a given tenant.
We want to add support for GET `/tenants?domain_name=wazo.community` and `/tenants?search=wazo`.
`search` is implicit.

2022-04-28 18:38 UTC, pc-m commented on wazo_auth/schemas.py
> +    sort_columns = ['name', 'slug', 'domain_name', 'domain_names', 'search_domain']
The `sort_columns` is used to validate which columns can be used for the sort argument or a request. I don't think we should modify it. Sorting by domain_names would be weird since we can have multiple `domain_names` on a given tenant.

2022-04-28 18:38 UTC, pc-m commented on integration_tests/suite/test_tenants.py
> +        matcher = contains_inanyorder(
Tests are telling you something here and you're telling the test to shutup about it.
The result of any request has the following format
```javascript
{
  'uuid': '94304416-2332-4617-bcae-c00f27e0411a',
  'parent_uuid': 'd5b20a36-0db2-484b-8587-d80a6a75af44',
  'name': 'foobaz',
  'slug': 'bbb',
  'contact': None,
  'phone': None,
  'domain_names': [
    '<wazo_auth.database.models.DomainName object at 0x7f5e90607850>', 
    '<wazo_auth.database.models.DomainName object at 0x7f5e90607b50>', 
    '<wazo_auth.database.models.DomainName object at 0x7f5e90607d50>'
  ],
  'address': {'line_1': None, 'line_2': None, 'city': None, 'state': None, 'country': None, 'zip_code': None}
}
```
The marshmallow schema should be modified to return the domain name instead of this. That will allow the test_post to work with a `contains_inanyorder` and avoid using `has_entries(uuid=` here to avoid comparing the other fields.

2022-04-28 23:37 UTC, nissou91 commented on wazo_auth/database/queries/tenant.py
> +            domain_name_strict_filter_ = Tenant.domain_names.any(
Thanks, took me a while to find it :)

2022-04-29 18:11 UTC, nissou91 commented on wazo_auth/schemas.py
> +    sort_columns = ['name', 'slug', 'domain_name', 'domain_names', 'search_domain']
I have kept `search_domain` as looking for a specific keyword in domain names using `search` does not work; however, when I put `search_domain` (like: `list(search_domain='yahoo')`), `list_` and `count` work perfectly. Also, you have to add it to searchable_columns in order for `test_list` method in `test_tenants.py` to work correctly.

2022-04-29 18:21 UTC, pc-m commented on wazo_auth/schemas.py
> +    sort_columns = ['name', 'slug', 'domain_name', 'domain_names', 'search_domain']
> I have kept `search_domain` as looking for a specific keyword in domain names using `search` does not work; however, when I put `search_domain` (like: `list(search_domain='yahoo')`), `list_` and `count` work perfectly. Also, you have to add it to searchable_columns in order for `test_list` method in `test_tenants.py` to work correctly.

Yeah I missed it during the review, you should change `_add_domain_filters` to handle `search` and `domain_name` only.

Our HTTP API does not have ways to do a fuzzy search on a given field. The only option should be `domain_name` for a strict domain name match or search for a fuzzy search on the domain names and all other searchable fields

2022-04-29 18:41 UTC, nissou91 commented on wazo_auth/schemas.py
> +    sort_columns = ['name', 'slug', 'domain_name', 'domain_names', 'search_domain']
could you please elaborate more your point? do you mean something like this?
```
def _add_domain_filters(self, search=None, domain_name=None, **ignored):
        if search:
            search_pattern = '%{}%'.format(search)
            domain_name_search_filter_ = Tenant.domains.any(
                DomainName.name.ilike(search_pattern)
            )
            return domain_name_search_filter_
        elif domain_name:
            domain_name_strict_filter_ = Tenant.domains.any(
                DomainName.name == domain_name
            )
            return domain_name_strict_filter_
        else:
            return text('true')
```

2022-05-04 21:29 UTC, pc-m approved these changes

2022-05-04 21:56 UTC, merged