tests: remove deprecated hamcrest.contains
wazo-platform/wazo-auth pull request #229
Opened 2022-06-15 15:13 UTC by sduthil

2022-06-16 11:26 UTC, xxbillouxx requested changes
Reviewed. gj

2022-06-16 13:37 UTC, sduthil commented on integration_tests/suite/helpers/base.py
>      assert_that(
`action` is a function like the others `fn` that runs an HTTP request. I prefer to change the other `fn` with `action` which is a bit more explicit.

2022-06-16 14:39 UTC, xxbillouxx commented on integration_tests/suite/helpers/base.py
>      assert_that(
`action`, without any context, has no meaning. So as a developer I prefer `fn`.

And as you said `action is a function` :-)

2022-06-17 14:50 UTC, xxbillouxx commented
recheck

2022-06-17 14:54 UTC, xxbillouxx approved these changes
gj

2022-06-17 15:28 UTC, merged