LDAP authentication is case-sensitive
wazo-platform/wazo-auth pull request #246
Opened 2022-08-17 18:11 UTC by nissou91

**Problem:**
* When we have a user comfigured within ldap configuration with the following email `awonderland@wazo-auth.com`, and this user tries to login with the same email address but containing upper case letters instead; like: `AWONDERLAND@WAZO-AUTH.COM` then it raises an HTTP 401 error code.

**Expected Behaviour:**
* We should accept any email address as long as they are the same when lowered.

2022-08-17 18:32 UTC, nissou91 commented
recheck

2022-08-22 19:26 UTC, bloom1 requested changes

2022-08-22 19:26 UTC, bloom1 commented on wazo_auth/plugins/backends/tests/test_ldap_user.py
> +        self.wazo_email = 'wazo.io'
I don't think it was necessary to extract this value in a variable - SonarCloud should be disabled (or consider it useless) for test files.

2022-08-22 19:26 UTC, bloom1 commented on wazo_auth/plugins/backends/ldap_user.py
> +        for user in self._user_service.list_users(tenant_uuid=tenant_uuid):
I would rather see this in the [list_](https://github.com/wazo-platform/wazo-auth/blob/WAZO-2852/wazo_auth/database/queries/user.py#L276) method. You can pretty much do like the other parameters extracted from the `kwargs` and do the lowercase comparison there. That would also allow the user search to be case insensitive when searching email addresses. In that case, you would also need to update the API documentation to reflect those changes.

2022-08-22 19:47 UTC, sboily commented on wazo_auth/plugins/backends/tests/test_ldap_user.py
> +        self.wazo_email = 'wazo.io'
No no, you don't disable Sonarcloud :), you just need to update it to ignore this.

2022-08-22 19:51 UTC, bloom1 commented on wazo_auth/plugins/backends/tests/test_ldap_user.py
> +        self.wazo_email = 'wazo.io'
> No no, you don't disable Sonarcloud :), you just need to update it to ignore this.

I think you misread what I wrote. I said that SonardCloud should be disabled for (to ignore) test files ;)

2022-08-22 19:53 UTC, sboily commented on wazo_auth/plugins/backends/tests/test_ldap_user.py
> +        self.wazo_email = 'wazo.io'
haha you right, the () has been considering a new phrase in my head. Sorry ;)

2022-08-22 21:35 UTC, nissou91 commented on wazo_auth/plugins/backends/tests/test_ldap_user.py
> +        self.wazo_email = 'wazo.io'
How do you achieve that? :)

2022-08-23 11:43 UTC, fblackburn1 reviewed
Why we change the whole wazo-auth implementation when the only requested change is for LDAP only?
Don't forget wazo-auth is used elsewhere ... and email address is unique with case sensitive.
Quick review of this PR add security issues

2022-08-23 14:14 UTC, bloom1 requested changes

2022-08-23 14:14 UTC, bloom1 commented on wazo_auth/plugins/backends/ldap_user.py
> +            if 'emails' in user.keys() and user['emails']:
It is possible (and better) to use `if user.get('emails')` :smiley:

2022-08-23 14:14 UTC, bloom1 commented on wazo_auth/database/queries/user.py
> +            )
We do not want to change the implementation for now - this will affect all of wazo-auth.
We should limit ourselves to the LDAP plugin for now, so we only want to lowercase what we get from the LDAP server.

2022-08-23 14:14 UTC, bloom1 commented on wazo_auth/plugins/backends/ldap_user.py
> +                if wazo_auth_user_email.lower() == user_email.lower():
We should not lowercase the email address from wazo-auth. If we do, we might have a situation where a wazo-auth user has the email address user@domain and another user with User@domain. We would not know which one to match and maybe we would login the wrong user. Leaving the case sensitivity on the wazo-auth side will allow the differentiation.

2022-08-23 14:22 UTC, nissou91 commented on wazo_auth/database/queries/user.py
> +            )
This will imply to remove this test scenario `test_ldap_authentication_works_when_case_sensitive_wazo_auth_user_email`; otherwise it will fail without this code change...

2022-08-23 14:28 UTC, bloom1 commented on wazo_auth/database/queries/user.py
> +            )
> This will imply to remove this test scenario `test_ldap_authentication_works_when_case_sensitive_wazo_auth_user_email`; otherwise it will fail without this code change...

Exactly.
The wazo-auth user email is not case insensitive. The LDAP one is :smile:

2022-08-23 14:36 UTC, nissou91 commented on wazo_auth/plugins/backends/ldap_user.py
> +                if wazo_auth_user_email.lower() == user_email.lower():
Done

2022-08-24 14:08 UTC, merged