[WP-749] ldap: add non-case-sensitive e-mail comparison wazo-auth side
wazo-platform/wazo-auth pull request #265
Opened 2023-01-17 21:24 UTC by bloom1

2023-01-20 13:47 UTC, pc-m requested changes
Could you add a test where we create multiple users

User 1: email = Foobar@example.com
User 2: email = FooBar@example.com
User 3: username = foobar@example.com

I would expect a 409 from the User 2 and User 3 creation as that would make the login unreliable for some of the users since only one would be check when creating a token.

2023-01-24 20:59 UTC, bloom1 commented
> 

This will be fixed and tested in WP-750

2023-01-27 16:59 UTC, sduthil commented on wazo_auth/database/queries/user.py
> +    def get_user_uuid_by_login(self, login, case_sensitive=True):
Do we really need a `case_sensitive` parameter?

2023-02-01 18:10 UTC, sduthil approved these changes

2023-02-01 18:11 UTC, merged