WAZO-3600: prevent thread crashing when removing tokens without tenant_uuid
wazo-platform/wazo-auth pull request #302
Opened 2024-01-15 19:11 UTC by ja0x

Why:

* Because the event requires a tenant_uuid, when none are provided (such as email reset token) the ExpiredTokenRemover thread crashes while trying to create it.

2024-01-16 14:43 UTC, fblackburn1 requested changes
Missing test

2024-01-19 12:53 UTC, fblackburn1 requested changes
Can you move test beside other expired token tests (`test_session.py`). It will avoid some confusion

2024-01-19 13:27 UTC, ja0x commented
Sure thing, didn't realize when I looked quickly there were some in test_sessions

2024-01-19 19:38 UTC, fblackburn1 approved these changes

2024-01-19 19:57 UTC, merged