WP 1386 add tests for the saml authentication
wazo-platform/wazo-auth pull request #323
Opened 2024-05-23 10:59 UTC by jirkah

2024-05-23 11:34 UTC, fblackburn1 commented on tox.ini
> +    #make test-setup
The PR will never pass if you comment `test-setup`

2024-05-30 18:59 UTC, sduthil requested changes

2024-05-30 18:59 UTC, sduthil commented on tox.ini
> +    pytest -m "not wazo_test_functional" {posargs:suite/}
I think the `-m` is not necessary, since the functional tests are isolated in the `functional_suite` directory.

2024-05-30 18:59 UTC, sduthil commented on tox.ini
> +    pytest -m wazo_test_functional {posargs:suite/}
I suggest moving the functional tests into `integration_tests/functional_suite/`, similarly to `performance_suite` and using:
```text
pytest {posargs:functional_suite/}
```

You will have to symlink any dependency used from `suite/` into `functional_suite/` for this to work though.

2024-05-30 18:59 UTC, sduthil commented on zuul.yaml
> +    pre-run: zuul.d/functional-pre-run.yaml
You also need to tell Zuul to use the new `tox` environment:
```suggestion
    pre-run: zuul.d/functional-pre-run.yaml
    tox_envlist: functional
```

2024-05-31 14:41 UTC, sduthil submitted a review, later dismissed

2024-05-31 14:41 UTC, sduthil commented
Approved for testing purposes only=

2024-05-31 14:55 UTC, sduthil submitted a review, later dismissed

2024-05-31 15:12 UTC, sduthil approved these changes

2024-05-31 15:23 UTC, sduthil approved these changes

2024-05-31 20:17 UTC, DrPyser reviewed
Added a commit to fix functional tests support for env. vars WAZO_SAML_LOGIN and WAZO_SAML_PASSWORD as per README.md

2024-05-31 20:23 UTC, DrPyser approved these changes

2024-05-31 20:40 UTC, merged