WAZO-2145: limit the number of sessions
wazo-platform/wazo-auth pull request #345
Opened 2024-06-19 13:26 UTC by ja0x

This PR proposes to introduce a maximum ceiling for the user's ability to create tokens/sessions.  

That maximum is configured in the config.py `max_users_concurrent_sessions` key and can be overriding in a configuration file but is not exposed by default

- By default, a user / external API users cannot create more than 100 tokens / sessions.  Beyond this limit a `429 Too many requests` response will be returned
- Internal users don't follow that limitation

2024-06-19 19:10 UTC, ja0x commented
recheck

2024-06-20 15:31 UTC, ja0x commented
recheck

2024-06-20 18:31 UTC, sduthil commented
The failing test comes from the commit message:
```
$ git log -1 HEAD --pretty=format:%s
fix typo (change users -> user)
```
`dch` interprets `->` as the option `>`...
I'm looking how to fix this

2024-06-20 18:40 UTC, sduthil commented
Fixed in https://github.com/TinxHQ/wazo-production-sf-jobs/pull/38

2024-06-20 18:41 UTC, sduthil commented
recheck

2024-06-20 18:49 UTC, sduthil requested changes

2024-06-20 18:54 UTC, ja0x commented on integration_tests/suite/test_token.py
> +        )
I agree

2024-06-20 18:58 UTC, ja0x commented on integration_tests/suite/test_token.py
> +        )
But it wouldn't get matched with the status_code as the 500 != 429

2024-06-25 18:35 UTC, sduthil approved these changes

2024-06-25 18:50 UTC, merged