WP-1387 API to configure SAML
wazo-platform/wazo-auth pull request #348
Opened 2024-06-20 16:15 UTC by jirkah

Depends-On: https://github.com/wazo-platform/wazo-auth-client/pull/52

2024-06-26 13:43 UTC, DrPyser commented on wazo_auth/database/queries/saml_config.py
> +        return self.session.query(SAMLConfig).filter(filter_).count() > 0
sql `EXISTS` with `.exists()` should produce optimal code for this use case.

2024-06-26 14:05 UTC, DrPyser commented on wazo_auth/database/queries/saml_config.py
> +from ... import exceptions
my opinion: relative imports hurt readability(complexify the job of understanding module dependencies).
Beyond the second degree of separation(`..`), I think we should stick to absolute paths, here `wazo_auth.exceptions`.

2024-06-26 14:12 UTC, DrPyser commented on wazo_auth/plugins/http/saml_config/http.py
> +                f"An error occurred while getting SAML ACS URL for tenant {scoping_tenant.uuid}."
```suggestion
                f"An error occurred while getting SAML ACS URL for tenant %s.", scoping_tenant.uuid
```

as a quirk of the logging system in python stdlib, it is preferred to write format strings using `%s`/ `%d` placeholders, and provide the format values as additional positional arguments after the format string. This allows the logging system to process the format string and the arguments, in principle allowing custom logic to make use of those separate pieces.

 I think this reflects existing conventions at wazo.

2024-06-26 14:15 UTC, DrPyser commented on wazo_auth/plugins/http/saml_config/schemas.py
> +    acsrl = fields.String(validate=Length(min=1, max=2083), required=True)
typo?
```suggestion
    acs_url = fields.String(validate=Length(min=1, max=2083), required=True)
```

2024-06-26 14:16 UTC, DrPyser commented on wazo_auth/services/saml.py
> +        # self._init_clients()
```suggestion
```

2024-06-26 14:19 UTC, DrPyser commented on wazo_auth/services/saml_config.py
> +        if domain_name[0]:
indexing empty array will result in `IndexError` exception.
```suggestion
        if domain_name:
```

2024-06-26 14:22 UTC, DrPyser commented on wazo_auth/services/saml_config.py
> +        assert f'Database consistency error, domain name for {item}/{domains}'
if the intent is to always yield an AssertionError at this point:
```suggestion
        assert False, f'Database consistency error, domain name for {item}/{domains}'
```

2024-06-26 14:23 UTC, DrPyser commented on wazo_auth/services/saml_config.py
> +
if the intent is to always produce an AssertionError at this point
```suggestion
        assert False, f'Database consistency error, domain name for {item}/{domains}'

```

2024-06-26 14:34 UTC, DrPyser commented on wazo_auth/services/saml_config.py
> +        saml_configs = [saml_config_schema.dump(item) for item in db_configs]
what is the goal/value of using marshmallow schema here?

I find it weird to use marshmallow schema to process data in internal logic. 
They are designed to process data at system boundaries, deserializing and validating data from the outside(API inputs) and serializing data to expose to the outside(API outputs).
For data from database, we already know its structure and should be able to assume it to be valid.

Also, marshmallow schemas don't expose typed interface, so we don't know what data we're getting and passing on, as far as type goes its just a dict or a list of dicts.

In this case, why not keep using the `SAMLConfig` sqlalchemy objects provided by the DAO, which at least have interfaces with known attributes?

2024-06-26 14:38 UTC, DrPyser commented on wazo_auth/services/saml_config.py
> +        saml_configs = [saml_config_schema.dump(item) for item in db_configs]
```suggestion
        saml_configs = [cast(SAMLDomainConfigDict, saml_config_schema.dump(item)) for item in db_configs]
```

2024-06-26 14:41 UTC, DrPyser commented on wazo_auth/services/saml_config.py
> +    def _update_item(self, item, domains) -> dict[str, str]:
Assuming
```
class SAMLDomainConfigDict(TypedDict):
    domain_uuid: str
    entity_id: str
    tenant_uuid: str
```

```suggestion
    def _update_item(self, item: SAMLDomainConfigDict, domains: list[Domain]) -> dict[str, str]:
```

2024-06-26 14:41 UTC, DrPyser commented on wazo_auth/services/saml_config.py
> +    def _add_metadata_path(self, item) -> dict[str, str]:
```suggestion
    def _add_metadata_path(self, item: SAMLDomainConfigDict) -> dict[str, str]:
```

2024-06-26 14:49 UTC, DrPyser commented on wazo_auth/services/saml_config.py
> +    def _update_item(self, item, domains) -> dict[str, str]:
I would also change the method name to something more descriptive.

i think I understand this transforms db data to a domain config, so how about `_make_domain_config_from_db`

2024-06-26 14:50 UTC, DrPyser commented on wazo_auth/services/saml_config.py
> +    def _update_domain_name(self, item, domains) -> dict[str, str]:
See other comments for `SAMLDBDomainConfigEntryDict`

```suggestion
    def _update_domain_name(self, item: SAMLDBDomainConfigEntryDict, domains: list[Domain]) -> dict[str, str]:
```

2024-06-26 14:53 UTC, DrPyser commented on wazo_auth/services/saml_config.py
> +    def _update_xml_metadata(
```suggestion
    def _write_xml_metadata_to_filesystem(
```

2024-06-26 14:55 UTC, DrPyser commented on wazo_auth/services/saml_config.py
> +        os.remove(self._xml_files_dir + '/' + tenant_uuid + '.xml')
Reuse `_get_metadata_path` for the path(avoid duplication of logic, guarantee correctness)
```suggestion
        os.remove(self._get_metadata_path)
```

2024-06-26 14:56 UTC, DrPyser commented on wazo_auth/services/saml_config.py
> +        self._reload_saml_service()
I see no reason not to call super first
```suggestion
        super().__init__(dao)
        self._xml_files_dir: str = config['saml']['xml_files_dir']
        self._saml_service = saml_service
        self._reload_saml_service()
```

2024-06-26 14:58 UTC, DrPyser commented on wazo_auth/services/saml_config.py
> +        self._xml_files_dir: str = config['saml']['xml_files_dir']
`xml_files_dir` is a new config attribute that is not otherwise declared in `wazo_auth.services.saml.WazoSAMLConfig`. Should be added there.

2024-06-26 15:19 UTC, DrPyser commented on wazo_auth/services/saml_config.py
> +    def __init__(self, config, saml_service, dao) -> None:
Assuming additional imports
```
from wazo_auth.database.queries import DAO
from wazo_auth.services.saml import Config, SAMLService
```

```suggestion
    def __init__(self, config: Config, saml_service: SAMLService, dao: DAO) -> None:
```

2024-07-16 19:04 UTC, pc-m requested changes
I spotted two missing tests. Charles also added some comments. I'd also like to be sure the the saml functional test keeps working since its not being executed by the CI at the moment

2024-07-17 12:20 UTC, pc-m approved these changes

2024-07-22 15:43 UTC, chartrandf commented
👀 (watch mode)

2024-07-24 18:47 UTC, pc-m approved these changes

2024-07-24 19:15 UTC, merged