WAZO-3795 persist saml sesion in database
wazo-platform/wazo-auth pull request #356
Opened 2024-07-17 14:02 UTC by jirkah

2024-07-25 14:11 UTC, jfbourque commented
recheck

2024-07-25 14:39 UTC, pc-m requested changes

2024-07-25 14:39 UTC, pc-m commented on wazo_auth/services/saml.py
> +        sessions: list[SamlSessionItem] = [
Why don't you allow list to accept a relay_state parameter and allow postgres to do the filtering?

2024-07-26 14:18 UTC, pc-m approved these changes

2024-07-26 14:32 UTC, merged